//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int Id { get; set; }
        public int Money { get; set; }
        public int Steel { get; set; }
        public int Titan { get; set; }
        public int Flora { get; set; }
        public int Energy { get; set; }
        public int Heat { get; set; }
        public string Owner { get; set; }
        public int GameId { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
